; handwritten code, feel free to modify anything here.
; for instance, here's some sample code that will overwrite team names

; --------------------
; example 1: set where we want to overwrite. here we'll overwrite the names for the Giants and some other teams
; the label "team_giants" is generated by Diz and you can use it here
; --------------------
; ORG txt_team_names_left_justified+$D2    ; this is at 0xC34755 (snes address) or offset 0x034914 in the ROM
; db "GHOSTKIDS", $00    ; was the brewers
; db "BALLPLAYR", $00
; db "  JUNKERS", $00
; db "  PRINCES", $00
; NOTE: i dont see the effect in-game but it definitely changes the bytes in the ROM. I must have the wrong table


; --------------------
; more complex example #2. the code at this location normally loads the address of the "LEFT JUSTIFIED" team names.
; if we overwrite it and force it to use another table containing right justified names, it'll demonstrate reading different
; addresses/etc
;
; you could also point this at a new copy of the code and overwrite the tables etc.
; if you use this, comment the above code
; --------------------
; ORG C1E971
; LDA.L txt_team_names_right_justified,X
; --------------------
; Plazma experimenting, bear with me, this won't be perfect
; ORG $C34202        ;
; db $01, $01, $17, $25, $74,
; Dom's command, pasted with the proper corrected bytes
; this tells Asar that anything that comes after begins overwriting the bytes at address $C7BD02
ORG $C7BD02

; now, whatever we write below will end up in C7BD02, (just like if we had edited them in HxD)
; let's stick a copy of the original table there:
; first couple entries of the table
db $01,$01,$13,$25,$74
db $01,$01,$14,$25,$74
db $01,$01,$15,$25,$74
db $01,$01,$16,$25,$74
db $01,$01,$17,$25,$74
db $01,$0B,$13,$25,$74
db $01,$0B,$14,$25,$74
db $01,$0B,$15,$25,$74
db $01,$0B,$16,$25,$74
db $01,$0B,$17,$25,$74
db $01,$17,$13,$25,$74
db $01,$17,$14,$25,$74
db $01,$17,$15,$25,$74
db $01,$17,$16,$25,$74
db $01,$17,$17,$25,$74,
db $00
db $01,$01,$13,$25,$74
db $01,$01,$14,$25,$74
db $01,$01,$15,$25,$74
db $01,$01,$16,$25,$74
db $01,$01,$17,$25,$74
db $01,$0B,$13,$25,$74
db $01,$0B,$14,$25,$74
db $01,$0B,$15,$25,$74
db $01,$0B,$16,$25,$74
db $01,$0B,$17,$25,$74
db $01,$16,$13,$25,$74
db $01,$16,$14,$25,$74
db $01,$16,$15,$25,$74
db $01,$16,$16,$25,$74
db $01,$16,$17,$25,$74
db $00,$02,$01,$03,$06

;This set changes the Team Names within the Table to the proper re-alignment.
ORG $C34683
db $44,$49,$41,$4D,$4F,$4E,$44,$42,$41,$43,$4B,$53,$00
db $52,$4F,$43,$4B,$49,$45,$53,$20,$20,$00
db $44,$4F,$44,$47,$45,$52,$53,$20,$20,$00
db $50,$41,$44,$52,$45,$53,$20,$20,$20,$00
db $47,$49,$41,$4E,$54,$53,$20,$20,$20,$00
db $43,$55,$42,$53,$20,$20,$20,$20,$20,$00
db $52,$45,$44,$53,$20,$20,$20,$20,$20,$00
db $42,$52,$45,$57,$45,$52,$53,$20,$20,$00
db $50,$49,$52,$41,$54,$45,$53,$20,$20,$00
db $43,$41,$52,$44,$49,$4E,$41,$4C,$53,$00
db $42,$52,$41,$56,$45,$53,$20,$20,$20,$00
db $4D,$41,$52,$4C,$49,$4E,$53,$20,$20,$00
db $4D,$45,$54,$53,$20,$20,$20,$20,$20,$00
db $50,$48,$49,$4C,$4C,$49,$45,$53,$20,$00
db $4E,$41,$54,$49,$4F,$4E,$41,$4C,$53,$00
db $41,$53,$54,$52,$4F,$53,$20,$20,$20,$00
db $41,$4E,$47,$45,$4C,$53,$20,$20,$20,$00
db $41,$54,$48,$4C,$45,$54,$49,$43,$53,$00
db $4D,$41,$52,$49,$4E,$45,$52,$53,$20,$00
db $52,$41,$4E,$47,$45,$52,$53,$20,$20,$00
db $57,$48,$49,$54,$45,$20,$53,$4F,$58,$00
db $47,$55,$41,$52,$44,$49,$41,$4E,$53,$00
db $54,$49,$47,$45,$52,$53,$20,$20,$20,$00
db $52,$4F,$59,$41,$4C,$53,$20,$20,$20,$00
db $54,$57,$49,$4E,$53,$20,$20,$20,$20,$00
db $4F,$52,$49,$4F,$4C,$45,$53,$20,$20,$00
db $52,$45,$44,$20,$53,$4F,$58,$20,$20,$00
db $59,$41,$4E,$4B,$45,$45,$53,$20,$20,$00
db $52,$41,$59,$53,$20,$20,$20,$20,$20,$00
db $42,$4C,$55,$45,$20,$4A,$41,$59,$53,$00
