; handwritten code, feel free to modify anything here.
; for instance, here's some sample code that will overwrite team names

; --------------------
; example 1: set where we want to overwrite. here we'll overwrite the names for the Giants and some other teams
; the label "team_giants" is generated by Diz and you can use it here
; --------------------
; ORG txt_team_names_left_justified+$D2    ; this is at 0xC34755 (snes address) or offset 0x034914 in the ROM
; db "GHOSTKIDS", $00    ; was the brewers
; db "BALLPLAYR", $00
; db "  JUNKERS", $00
; db "  PRINCES", $00
; NOTE: i dont see the effect in-game but it definitely changes the bytes in the ROM. I must have the wrong table


; --------------------
; more complex example #2. the code at this location normally loads the address of the "LEFT JUSTIFIED" team names.
; if we overwrite it and force it to use another table containing right justified names, it'll demonstrate reading different
; addresses/etc
;
; you could also point this at a new copy of the code and overwrite the tables etc.
; if you use this, comment the above code
; --------------------
; ORG C1E971
; LDA.L txt_team_names_right_justified,X